/**
 * Report.java
 * Represents a sales and activity report in the Flight Management System.
 * Stores aggregated data about ticket sales, revenue, and bookings.
 * Reports are generated by the system administrator to monitor
 * the overall performance of the platform.
 *
 * Author: Adrian Salgado
 * Date: 04/27/2026
 * Course: CS 3321 - Software Engineering
 */

package com.flightmanagement.models;

public class Report {

    private String reportID;
    private String reportType;     // "SALES", "REVENUE", "BOOKING"
    private String generatedDate;
    private double totalSales;
    private double totalRevenue;
    private int bookingCount;

    // Default constructor
    public Report() {}

    // Parameterized constructor for a fully initialized report
    public Report(String reportID, String reportType, String generatedDate,
                  double totalSales, double totalRevenue, int bookingCount) {
        this.reportID = reportID;
        this.reportType = reportType;
        this.generatedDate = generatedDate;
        this.totalSales = totalSales;
        this.totalRevenue = totalRevenue;
        this.bookingCount = bookingCount;
    }

    /**
     * Generates and displays the report based on its type.
     * Formats the output differently depending on report type.
     */
    public void generate() {
        System.out.println("Generating " + reportType + " report...");
        System.out.println("Report ID: " + reportID);
        System.out.println("Generated Date: " + generatedDate);

        // display different details based on the report type
        if (reportType.equals("SALES")) {
            System.out.println("Total Sales: $" + totalSales);
            System.out.println("Total Bookings: " + bookingCount);
        } else if (reportType.equals("REVENUE")) {
            System.out.println("Total Revenue: $" + totalRevenue);
        } else if (reportType.equals("BOOKING")) {
            System.out.println("Total Bookings: " + bookingCount);
            System.out.println("Total Revenue: $" + totalRevenue);
        }
    }

    /**
     * Exports the report as a formatted string.
     * Can be used to save or print the report.
     */
    public String export() {
        return "========== " + reportType + " REPORT ==========" +
               "\nReport ID     : " + reportID +
               "\nGenerated Date: " + generatedDate +
               "\nTotal Sales   : $" + totalSales +
               "\nTotal Revenue : $" + totalRevenue +
               "\nTotal Bookings: " + bookingCount +
               "\n==========================================";
    }

    /**
     * Returns a short summary of this report.
     * Used when listing reports in the admin dashboard.
     */
    public String getReportSummary() {
        return "Report ID: " + reportID +
               " | Type: " + reportType +
               " | Date: " + generatedDate +
               " | Revenue: $" + totalRevenue +
               " | Bookings: " + bookingCount;
    }

    // Getters
    public String getReportID() { return reportID; }
    public String getReportType() { return reportType; }
    public String getGeneratedDate() { return generatedDate; }
    public double getTotalSales() { return totalSales; }
    public double getTotalRevenue() { return totalRevenue; }
    public int getBookingCount() { return bookingCount; }

    // Setters
    public void setReportID(String reportID) { this.reportID = reportID; }
    public void setReportType(String reportType) { this.reportType = reportType; }
    public void setGeneratedDate(String generatedDate) { this.generatedDate = generatedDate; }
    public void setTotalSales(double totalSales) { this.totalSales = totalSales; }
    public void setTotalRevenue(double totalRevenue) { this.totalRevenue = totalRevenue; }
    public void setBookingCount(int bookingCount) { this.bookingCount = bookingCount; }
}
